// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_STATUS_UNSET Status = 0
	Status_CREATED      Status = 1
	Status_DONE         Status = 2
)

var Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "CREATED",
	2: "DONE",
}

var Status_value = map[string]int32{
	"STATUS_UNSET": 0,
	"CREATED":      1,
	"DONE":         2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

type Todo struct {
	TodoId               string               `protobuf:"bytes,1,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	Status               Status               `protobuf:"varint,2,opt,name=status,proto3,enum=todo.Status" json:"status,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetTodoId() string {
	if m != nil {
		return m.TodoId
	}
	return ""
}

func (m *Todo) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_STATUS_UNSET
}

func (m *Todo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Todo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("todo.Status", Status_name, Status_value)
	proto.RegisterType((*Todo)(nil), "todo.Todo")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x31, 0x6f, 0xc2, 0x30,
	0x10, 0x85, 0x6b, 0x1a, 0x25, 0xe5, 0x40, 0x55, 0x74, 0x4b, 0x2d, 0x96, 0x46, 0x55, 0x87, 0xa8,
	0x83, 0x51, 0xe9, 0xd4, 0x31, 0x2a, 0x19, 0xba, 0x50, 0xc9, 0x36, 0x73, 0x64, 0xb0, 0x8b, 0x90,
	0x0a, 0x87, 0xc8, 0xf1, 0x67, 0xfa, 0x6b, 0x51, 0x1c, 0xb2, 0xf9, 0x3d, 0xbf, 0x77, 0xef, 0x03,
	0x60, 0xf2, 0xa4, 0x4e, 0x67, 0x62, 0xc2, 0xa4, 0x7b, 0xcf, 0x9e, 0x77, 0x44, 0xbb, 0xbf, 0x30,
	0x8f, 0xde, 0xe6, 0xf2, 0x3b, 0xe7, 0xfd, 0x21, 0xb4, 0xec, 0x0e, 0xa7, 0x3e, 0xf6, 0xf2, 0x2f,
	0x20, 0xb1, 0xe4, 0x09, 0x9f, 0x20, 0xeb, 0x1a, 0xcd, 0xde, 0x4b, 0x51, 0x88, 0x72, 0xac, 0xd3,
	0x4e, 0x7e, 0x7b, 0x7c, 0x85, 0xb4, 0x65, 0xc7, 0x97, 0x56, 0x8e, 0x0a, 0x51, 0x3e, 0x2e, 0xa6,
	0x2a, 0xae, 0x98, 0xe8, 0xe9, 0xdb, 0x1f, 0x4a, 0xc8, 0xb6, 0x74, 0xe4, 0x70, 0x64, 0x79, 0x1f,
	0xeb, 0x83, 0xc4, 0x4f, 0x80, 0xed, 0x39, 0x38, 0x0e, 0xbe, 0x71, 0x2c, 0x93, 0x42, 0x94, 0x93,
	0xc5, 0x4c, 0xf5, 0x5c, 0x6a, 0xe0, 0x52, 0x76, 0xe0, 0xd2, 0xe3, 0x5b, 0xba, 0xe2, 0xb7, 0x77,
	0x48, 0xfb, 0x19, 0xcc, 0x61, 0x6a, 0x6c, 0x65, 0xd7, 0xa6, 0x59, 0xaf, 0x4c, 0x6d, 0xf3, 0x3b,
	0x9c, 0x40, 0xf6, 0xa5, 0xeb, 0xca, 0xd6, 0xcb, 0x5c, 0xe0, 0x03, 0x24, 0xcb, 0x9f, 0x55, 0x9d,
	0x8f, 0x36, 0x69, 0xbc, 0xf8, 0x71, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xd2, 0xb5, 0x06, 0x0b,
	0x01, 0x00, 0x00,
}
